export const loginData = {
  title: "Login To Continue",
  fields: [
    {
      name: "username",
      type: ["text", "email"],
      label: "Username",
      required: true,
    },
    {
      name: "password",
      type: "password",
      label: "Password",
      required: true,
    },
    {
      name: "rememberMe",
      type: "checkbox",
      label: "Remember Me",
      required: false,
    },
  ],
};
export const signupData = {
  title: "Signup To Explore More",
  fields: [
    {
      name: "firstName",
      type: "text",
      label: "First Name",
      id: "firstName",
      labelFor: "firstName",
      required: true,
    },
    {
      name: "lastName",
      type: "text",
      label: "Last Name",
      id: "lastName",
      labelFor: "lastName",
      required: true,
    },
    {
      name: "username",
      type: "text",
      label: "Username",
      id: "username",
      labelFor: "username",
      required: true,
    },
    {
      label: "Gender",
      options: [
        {
          name: "gender",
          type: "radio",
          label: "Male",
          value: "male",
          id: "male",
          labelFor: "male",
          required: true,
        },
        {
          name: "gender",
          type: "radio",
          label: "Female",
          value: "Female",
          id: "female",
          labelFor: "female",
          required: true,
        },
        {
          name: "gender",
          type: "radio",
          label: "Others",
          value: "Others",
          id: "others",
          labelFor: "others",
          required: true,
        },
      ],
    },
    {
      name: "email",
      type: "email",
      label: "Email",
      id: "email",
      labelFor: "email",
      required: true,
    },
    {
      name: "contact",
      type: "tel",
      label: "Contact",
      id: "contact",
      labelFor: "contact",
      required: true,
    },
    {
      name: "password",
      type: "password",
      label: "Password",
      id: "password",
      labelFor: "password",
      required: true,
    },
    {
      name: "confirmPwd",
      type: "password",
      label: "Confirm Password",
      id: "confirmPwd",
      labelFor: "confirmPwd",
      required: true,
    },
    {
      name: "profile",
      type: "file",
      // label: "Upload Your Photo",
    },
    {
      name: "acceptTerms",
      type: "checkbox",
      label: "I agree to the Terms & Conditions and Privacy Policy",
      id: "acceptTerms",
      required: true,
    },
  ],
};
